import Toffoli.Bool.Reindex
import Toffoli.Component.Tensor

/-!
# One-to-one circuit composition

This syntax records exactly the resource-free operations allowed by the paper's no-fan-out
composition discipline. Its evaluator uses ordinary equivalence composition; the syntax is not a
second semantic notion of function composition.

`wire` is a bare permutation of component labels. `reindex` instead transports an entire circuit
between equivalent index types by conjugating its evaluated permutation. These operations differ,
including in parity at low arities.
-/

namespace Toffoli

universe u v

/-- Resource-free one-to-one circuits generated by a type-indexed family of primitive gates. -/
inductive OneToOneCircuit (Atom : Type u → Type v) : Type u → Type (max (u + 1) v)
  | identity {ι : Type u} : OneToOneCircuit Atom ι
  | primitive {ι : Type u} (gate : Atom ι) : OneToOneCircuit Atom ι
  | wire {ι : Type u} (wiring : Equiv.Perm ι) : OneToOneCircuit Atom ι
  | serial {ι : Type u} (first second : OneToOneCircuit Atom ι) : OneToOneCircuit Atom ι
  | tensor {ι κ : Type u} (left : OneToOneCircuit Atom ι) (right : OneToOneCircuit Atom κ) :
      OneToOneCircuit Atom (ι ⊕ κ)
  | reindex {ι κ : Type u} (e : ι ≃ κ) (circuit : OneToOneCircuit Atom ι) :
      OneToOneCircuit Atom κ

namespace OneToOneCircuit

variable {Atom : Type u → Type v}

/-- Evaluate a one-to-one circuit as an ordinary Boolean permutation. Serial composition applies
the first circuit and then the second. -/
def eval (atomEval : {ι : Type u} → Atom ι → BoolPerm ι) :
    {ι : Type u} → OneToOneCircuit Atom ι → BoolPerm ι
  | _, .identity => Equiv.refl _
  | _, .primitive gate => atomEval gate
  | _, .wire wiring => BoolPerm.coordinatePerm wiring
  | _, .serial first second => (eval atomEval first).trans (eval atomEval second)
  | _, .tensor left right => BoolPerm.tensor (eval atomEval left) (eval atomEval right)
  | _, .reindex e circuit => BoolPerm.reindex e (eval atomEval circuit)

@[simp]
theorem eval_identity (atomEval : {ι : Type u} → Atom ι → BoolPerm ι) (ι : Type u) :
    eval atomEval (identity : OneToOneCircuit Atom ι) = Equiv.refl _ :=
  rfl

@[simp]
theorem eval_primitive (atomEval : {ι : Type u} → Atom ι → BoolPerm ι) {ι : Type u}
    (gate : Atom ι) : eval atomEval (.primitive gate) = atomEval gate :=
  rfl

@[simp]
theorem eval_wire (atomEval : {ι : Type u} → Atom ι → BoolPerm ι) {ι : Type u}
    (wiring : Equiv.Perm ι) : eval atomEval (.wire wiring) = BoolPerm.coordinatePerm wiring :=
  rfl

@[simp]
theorem eval_serial (atomEval : {ι : Type u} → Atom ι → BoolPerm ι) {ι : Type u}
    (first second : OneToOneCircuit Atom ι) :
    eval atomEval (.serial first second) = (eval atomEval first).trans (eval atomEval second) :=
  rfl

@[simp]
theorem eval_tensor (atomEval : {ι : Type u} → Atom ι → BoolPerm ι) {ι κ : Type u}
    (left : OneToOneCircuit Atom ι) (right : OneToOneCircuit Atom κ) :
    eval atomEval (.tensor left right) =
      BoolPerm.tensor (eval atomEval left) (eval atomEval right) :=
  rfl

@[simp]
theorem eval_reindex (atomEval : {ι : Type u} → Atom ι → BoolPerm ι) {ι κ : Type u}
    (e : ι ≃ κ) (circuit : OneToOneCircuit Atom ι) :
    eval atomEval (.reindex e circuit) = BoolPerm.reindex e (eval atomEval circuit) :=
  rfl

theorem eval_reindex_reindex (atomEval : {ι : Type u} → Atom ι → BoolPerm ι)
    {ι κ μ : Type u} (e : ι ≃ κ) (f : κ ≃ μ) (circuit : OneToOneCircuit Atom ι) :
    eval atomEval (.reindex f (.reindex e circuit)) =
      eval atomEval (.reindex (e.trans f) circuit) := by
  exact (BoolPerm.reindex_trans e f (eval atomEval circuit)).symm

theorem eval_wire_serial (atomEval : {ι : Type u} → Atom ι → BoolPerm ι) {ι : Type u}
    (e f : Equiv.Perm ι) :
    eval atomEval (.serial (.wire e) (.wire f)) =
      eval atomEval (.wire (e.trans f)) := by
  exact (BoolWord.reindex_trans e f).symm

end OneToOneCircuit

end Toffoli
