import Mathlib.Algebra.Group.Subgroup.Ker
import Toffoli.Bool.Finite
import Toffoli.Parity.Obstruction
import Toffoli.Parity.Wiring

/-!
# The paper's lower-order generator set

This leaf adds the bare coordinate wirings allowed by the paper's one-to-one composition
convention.  The parity proof is valid from three ambient bits onward.  Arity two needs a separate
global-complement invariant because its coordinate swap is odd; arities zero and one are handled
directly.
-/

namespace Toffoli

namespace BoolPerm

/-- Complement every component. -/
def globalNotOn (ι : Type*) : BoolPerm ι :=
  BoolWord.flipMaskEquiv fun _ => true

/-- Complement every component of an `n`-bit word. -/
abbrev globalNot (n : ℕ) : BoolPermN n := globalNotOn (Fin n)

@[simp]
theorem globalNotOn_apply {ι : Type*} (x : BoolWord ι) (i : ι) :
    globalNotOn ι x i = !(x i) := by
  simp [globalNotOn, BoolWord.flipMaskEquiv, BoolWord.flipMask]

theorem coordinatePerm_commute_globalNot (n : ℕ) (e : Equiv.Perm (Fin n)) :
    Commute (coordinatePerm e) (globalNot n) := by
  apply Equiv.ext
  intro x
  funext i
  rfl

theorem reindex_globalNotOn {ι κ : Type*} (e : ι ≃ κ) :
    reindex e (globalNotOn ι) = globalNotOn κ := by
  apply Equiv.ext
  intro x
  funext i
  simp [reindex_apply, globalNotOn_apply]

private theorem reindex_mul {ι κ : Type*} (e : ι ≃ κ) (p q : BoolPerm ι) :
    reindex e (p * q) = reindex e p * reindex e q := by
  rw [Equiv.Perm.mul_def, Equiv.Perm.mul_def]
  exact reindex_serial e q p

theorem reindex_commute_globalNotOn {ι κ : Type*} (e : ι ≃ κ)
    {p : BoolPerm ι} (hp : Commute p (globalNotOn ι)) :
    Commute (reindex e p) (globalNotOn κ) := by
  rw [← reindex_globalNotOn e]
  change reindex e p * reindex e (globalNotOn ι) =
    reindex e (globalNotOn ι) * reindex e p
  rw [← reindex_mul, hp.eq, reindex_mul]

end BoolPerm

/-- An arbitrary smaller permutation placed on ambient wires, with a nonempty unused factor. -/
def IsProperPlacement (n : ℕ) (g : BoolPermN n) : Prop :=
  ∃ active unused : ℕ, 0 < unused ∧
    ∃ (p : BoolPermN active) (e : Fin active ⊕ Fin unused ≃ Fin n),
      g = BoolPerm.reindex e (BoolPerm.extendRight p (Fin unused))

/-- The exact proper-order AND/NAND placements used in the paper. -/
def IsProperAndNandPlacement (n : ℕ) (g : BoolPermN n) : Prop :=
  ∃ controls unused : ℕ, 0 < unused ∧
    ∃ e : Fin (controls + 1) ⊕ Fin unused ≃ Fin n,
      g = BoolPerm.reindex e
        (BoolPerm.extendRight (AndNand.thetaSucc controls) (Fin unused))

/-- A bare permutation of coordinate labels, as opposed to conjugating one local gate. -/
def IsCoordinateWiring (n : ℕ) (g : BoolPermN n) : Prop :=
  ∃ e : Equiv.Perm (Fin n), g = BoolPerm.coordinatePerm e

/-- The paper's proper-order AND/NAND gates together with bare coordinate wiring. -/
def paperGenerator (n : ℕ) : Set (BoolPermN n) :=
  {g | IsProperAndNandPlacement n g ∨ IsCoordinateWiring n g}

/-- Group generated by the paper's allowed lower-order gates and coordinate wirings. -/
def paperGenerated (n : ℕ) : Subgroup (BoolPermN n) :=
  Subgroup.closure (paperGenerator n)

/-- The even Boolean permutations. -/
def evenSubgroup (n : ℕ) : Subgroup (BoolPermN n) :=
  Equiv.Perm.sign.ker

/-- Permutations commuting with global bitwise complement. -/
def globalNotCentralizer (n : ℕ) : Subgroup (BoolPermN n) where
  carrier := {p | Commute p (BoolPerm.globalNot n)}
  one_mem' := Commute.one_left _
  mul_mem' hp hq := hp.mul_left hq
  inv_mem' hp := hp.inv_left

theorem isProperPlacement_even {n : ℕ} {g : BoolPermN n}
    (hg : IsProperPlacement n g) : Equiv.Perm.sign g = 1 := by
  rcases hg with ⟨active, unused, hunused, p, e, rfl⟩
  haveI : Nonempty (Fin unused) := ⟨⟨0, hunused⟩⟩
  rw [BoolPerm.sign_reindex, BoolPerm.sign_extendRight_of_nonempty]

theorem isProperAndNandPlacement_isProperPlacement {n : ℕ} {g : BoolPermN n}
    (hg : IsProperAndNandPlacement n g) : IsProperPlacement n g := by
  rcases hg with ⟨controls, unused, hunused, e, rfl⟩
  exact ⟨controls + 1, unused, hunused, AndNand.thetaSucc controls, e, rfl⟩

/-! ## The two-bit exception: a complement invariant replaces parity -/

theorem thetaSucc_zero_extend_commute_globalNot :
    Commute (BoolPerm.extendRight (AndNand.thetaSucc 0) (Fin 1))
      (BoolPerm.globalNotOn (Fin 1 ⊕ Fin 1)) := by
  apply Equiv.ext
  intro x
  funext i
  cases i with
  | inl j =>
      have hj : j = 0 := Fin.eq_zero j
      subst j
      simp [Equiv.Perm.mul_apply, BoolPerm.extendRight_apply_inl]
  | inr j =>
      simp [Equiv.Perm.mul_apply, BoolPerm.extendRight_apply_inr]

theorem isProperAndNandPlacement_two_commutes {g : BoolPermN 2}
    (hg : IsProperAndNandPlacement 2 g) : Commute g (BoolPerm.globalNot 2) := by
  rcases hg with ⟨controls, unused, hunused, e, rfl⟩
  have hcard := Fintype.card_congr e
  simp only [Fintype.card_sum, Fintype.card_fin] at hcard
  have hcontrols : controls = 0 := by omega
  have hunused_one : unused = 1 := by omega
  subst controls
  subst unused
  exact BoolPerm.reindex_commute_globalNotOn e thetaSucc_zero_extend_commute_globalNot

theorem paperGenerator_two_mem_globalNotCentralizer {g : BoolPermN 2}
    (hg : g ∈ paperGenerator 2) : g ∈ globalNotCentralizer 2 := by
  rcases hg with hg | hg
  · exact isProperAndNandPlacement_two_commutes hg
  · rcases hg with ⟨e, rfl⟩
    exact BoolPerm.coordinatePerm_commute_globalNot 2 e

theorem paperGenerated_two_le_globalNotCentralizer :
    paperGenerated 2 ≤ globalNotCentralizer 2 := by
  apply (Subgroup.closure_le (globalNotCentralizer 2)).2
  exact fun _ hg => paperGenerator_two_mem_globalNotCentralizer hg

theorem thetaSucc_one_not_commute_globalNot :
    ¬Commute (AndNand.thetaSucc 1) (BoolPerm.globalNot 2) := by
  intro h
  let z : BoolVec 2 := fun _ => false
  have hval := congrArg (fun p : BoolPermN 2 => p z (Fin.last 1)) h.eq
  change AndNand.thetaSucc 1 (BoolPerm.globalNot 2 z) (Fin.last 1) =
    BoolPerm.globalNot 2 (AndNand.thetaSucc 1 z) (Fin.last 1) at hval
  have hglobalz : BoolPerm.globalNot 2 z = (fun _ => true) := by
    funext i
    simp [z]
  rw [hglobalz, BoolPerm.globalNotOn_apply, AndNand.thetaSucc_apply_target,
    AndNand.thetaSucc_apply_target] at hval
  simp at hval

/-- At arity two, the lower gates plus the odd wire swap still cannot generate CNOT. -/
theorem thetaSucc_one_not_mem_paperGenerated :
    AndNand.thetaSucc 1 ∉ paperGenerated 2 := by
  intro hmem
  exact thetaSucc_one_not_commute_globalNot
    (paperGenerated_two_le_globalNotCentralizer hmem)

/-! ## Arity one and zero -/

theorem isProperAndNandPlacement_one_false {g : BoolPermN 1}
    (hg : IsProperAndNandPlacement 1 g) : False := by
  rcases hg with ⟨controls, unused, hunused, e, _⟩
  have hcard := Fintype.card_congr e
  simp only [Fintype.card_sum, Fintype.card_fin] at hcard
  omega

theorem coordinatePerm_finOne_eq_refl (e : Equiv.Perm (Fin 1)) :
    BoolPerm.coordinatePerm e = Equiv.refl _ := by
  apply Equiv.ext
  intro x
  funext i
  rw [BoolPerm.coordinatePerm_apply]
  congr
  exact Subsingleton.elim _ _

theorem paperGenerator_one_eq_refl {g : BoolPermN 1} (hg : g ∈ paperGenerator 1) :
    g = 1 := by
  rcases hg with hg | hg
  · exact (isProperAndNandPlacement_one_false hg).elim
  · rcases hg with ⟨e, rfl⟩
    simpa [Equiv.Perm.one_def] using coordinatePerm_finOne_eq_refl e

theorem paperGenerated_one_eq_bot : paperGenerated 1 = ⊥ := by
  apply le_antisymm
  · apply (Subgroup.closure_le (⊥ : Subgroup (BoolPermN 1))).2
    intro g hg
    simpa using paperGenerator_one_eq_refl hg
  · exact bot_le

/-- At arity one, NOT is not generated by the empty lower-order gate family. -/
theorem thetaSucc_zero_not_mem_paperGenerated :
    AndNand.thetaSucc 0 ∉ paperGenerated 1 := by
  rw [paperGenerated_one_eq_bot]
  intro heq
  have hsign := congrArg Equiv.Perm.sign heq
  have hodd : Equiv.Perm.sign (AndNand.thetaSucc 0) = -1 := by
    simpa [AndNand.thetaSucc, AndNand.thetaSuccSpec, ToffoliGate.andNand]
      using sign_andNand (0 : Fin 1)
  rw [hodd, Equiv.Perm.sign_one] at hsign
  exact (by decide : (-1 : ℤˣ) ≠ 1) hsign

/-- At arity zero the Boolean cube is a singleton, so the generated subgroup is already all of
the permutation group and no obstruction exists. -/
theorem paperGenerated_zero_eq_top : paperGenerated 0 = ⊤ := by
  apply top_unique
  intro p _
  rw [boolPermN_zero_eq_refl p]
  exact Subgroup.one_mem _

/-! ## Three or more bits: the corrected parity argument -/

theorem paperGenerator_even (k : ℕ) (hk : 0 < k) {g : BoolPermN (2 + k)}
    (hg : g ∈ paperGenerator (2 + k)) : Equiv.Perm.sign g = 1 := by
  rcases hg with hg | hg
  · exact isProperPlacement_even (isProperAndNandPlacement_isProperPlacement hg)
  · rcases hg with ⟨e, rfl⟩
    exact BoolPerm.sign_coordinatePerm_eq_one k hk e

theorem paperGenerated_le_evenSubgroup (k : ℕ) (hk : 0 < k) :
    paperGenerated (2 + k) ≤ evenSubgroup (2 + k) := by
  apply (Subgroup.closure_le (evenSubgroup (2 + k))).2
  intro g hg
  change Equiv.Perm.sign g = 1
  exact paperGenerator_even k hk hg

/-- From three ambient bits onward, every paper generator is even, so no full-arity atomic edge
belongs to the generated subgroup. -/
theorem atomicEdge_not_mem_paperGenerated (k : ℕ) (hk : 0 < k)
    (x : BoolVec (2 + k)) (target : Fin (2 + k)) :
    atomicEdge x target ∉ paperGenerated (2 + k) := by
  intro hmem
  have heven := paperGenerated_le_evenSubgroup k hk hmem
  change Equiv.Perm.sign (atomicEdge x target) = 1 at heven
  rw [sign_atomicEdge] at heven
  exact (by decide : (-1 : ℤˣ) ≠ 1) heven

end Toffoli
