import Toffoli.Circuit.ThreeBit
import Toffoli.Synthesis.FaceRealization

/-!
# Structural obstruction with one auxiliary bit

On three ambient wires, a placed three-bit Toffoli cannot act on a word containing at most one
`true` bit: its two distinct positive controls cannot both be active.  Bare coordinate wirings and
serial composition preserve the same property.  This yields a structural obstruction to realizing
the double-NOT permutation on two data bits with only one fixed auxiliary bit, even when the input
and output auxiliary constants may differ.
-/

namespace Toffoli

universe u

namespace Synthesis

variable {ι : Type u}

/-- A Boolean word has at most one true coordinate.  This formulation does not require finiteness
of the coordinate type. -/
def AtMostOneTrue (x : BoolWord ι) : Prop :=
  ∀ ⦃i j : ι⦄, x i = true → x j = true → i = j

/-- A Boolean permutation preserves the at-most-one-true invariant. -/
def PreservesAtMostOneTrue (p : BoolPerm ι) : Prop :=
  ∀ ⦃x : BoolWord ι⦄, AtMostOneTrue x → AtMostOneTrue (p x)

namespace PreservesAtMostOneTrue

/-- Identity preserves the invariant. -/
theorem identity : PreservesAtMostOneTrue (Equiv.refl (BoolWord ι)) := by
  intro x hx
  exact hx

/-- Bare coordinate wiring preserves the invariant. -/
theorem wiring (wiring : Equiv.Perm ι) :
    PreservesAtMostOneTrue (BoolPerm.coordinatePerm wiring) := by
  intro x hx i j hi hj
  change x (wiring.symm i) = true at hi
  change x (wiring.symm j) = true at hj
  exact wiring.symm.injective (hx hi hj)

/-- A placed three-bit Toffoli preserves the invariant.  In fact it fixes every word satisfying
the invariant because its distinct controls cannot both be true. -/
theorem instruction [DecidableEq ι] (gate : ThreeBitInstruction ι) :
    PreservesAtMostOneTrue gate.perm := by
  intro x hx
  have hinactive : ¬gate.gate.Active x := by
    rw [gate.gate_active_iff]
    rintro ⟨hcontrol₁, hcontrol₂⟩
    exact gate.control₁_ne_control₂ (hx hcontrol₁ hcontrol₂)
  have hfixed : gate.perm x = x := (gate.gate.perm_eq_self_iff x).2 hinactive
  rw [hfixed]
  exact hx

/-- Serial composition preserves the invariant when each factor does.  The first permutation acts
first, in agreement with `Equiv.trans`. -/
theorem serial {first second : BoolPerm ι} (hfirst : PreservesAtMostOneTrue first)
    (hsecond : PreservesAtMostOneTrue second) :
    PreservesAtMostOneTrue (first.trans second) := by
  intro x hx
  exact hsecond (hfirst hx)

end PreservesAtMostOneTrue

/-- The fixed-ambient serial closure generated by placed three-bit Toffoli instructions and bare
coordinate wirings.  There is no tensoring, restriction, or change of ambient coordinate type
inside this closure. -/
inductive ThreeBitGenerated (ι : Type u) [DecidableEq ι] : BoolPerm ι → Prop
  | identity : ThreeBitGenerated ι (Equiv.refl (BoolWord ι))
  | instruction (gate : ThreeBitInstruction ι) : ThreeBitGenerated ι gate.perm
  | wiring (wiring : Equiv.Perm ι) :
      ThreeBitGenerated ι (BoolPerm.coordinatePerm wiring)
  | serial {first second : BoolPerm ι} :
      ThreeBitGenerated ι first → ThreeBitGenerated ι second →
        ThreeBitGenerated ι (first.trans second)

namespace ThreeBitGenerated

variable [DecidableEq ι]

/-- Every permutation in the fixed-ambient generated closure preserves the at-most-one-true
invariant. -/
theorem preservesAtMostOneTrue {p : BoolPerm ι} (hp : ThreeBitGenerated ι p) :
    PreservesAtMostOneTrue p := by
  induction hp with
  | identity => exact PreservesAtMostOneTrue.identity
  | instruction gate => exact PreservesAtMostOneTrue.instruction gate
  | wiring wiring => exact PreservesAtMostOneTrue.wiring wiring
  | serial _ _ hfirst hsecond => exact hfirst.serial hsecond

end ThreeBitGenerated

/-- Simultaneously complement both bits of a two-bit word. -/
def twoBitDoubleNot : BoolPerm (Fin 2) where
  toFun x i := !(x i)
  invFun x i := !(x i)
  left_inv x := by simp
  right_inv x := by simp

@[simp]
theorem twoBitDoubleNot_apply (x : BoolWord (Fin 2)) (i : Fin 2) :
    twoBitDoubleNot x i = !(x i) :=
  rfl

/-- Two zero data bits together with an arbitrary single auxiliary constant satisfy the global
at-most-one-true invariant. -/
theorem zeroDataWithOneAux_atMostOneTrue (input : BoolWord (Fin 1)) :
    AtMostOneTrue
      (BoolWord.sumEquiv.symm ((fun _ : Fin 2 ↦ false), input)) := by
  intro i j hi hj
  cases i with
  | inl i => simp at hi
  | inr k =>
      cases j with
      | inl j => simp at hj
      | inr l =>
          exact congrArg (Sum.inr : Fin 1 → Fin 2 ⊕ Fin 1) (Subsingleton.elim k l)

/-- Double-NOT sends the zero data word to a word with two true data coordinates, independently of
the auxiliary output constant. -/
theorem twoBitDoubleNot_zero_not_atMostOneTrue (output : BoolWord (Fin 1)) :
    ¬AtMostOneTrue
      (BoolWord.sumEquiv.symm
        (twoBitDoubleNot (fun _ : Fin 2 ↦ false), output)) := by
  intro h
  have heq := h (i := Sum.inl (0 : Fin 2)) (j := Sum.inl (1 : Fin 2)) (by rfl) (by rfl)
  exact (by decide : (Sum.inl (0 : Fin 2) : Fin 2 ⊕ Fin 1) ≠ Sum.inl (1 : Fin 2)) heq

/-- No fixed-ambient serial circuit generated by placed three-bit Toffoli gates and bare coordinate
wirings on `Fin 2 ⊕ Fin 1` realizes two-bit double-NOT with one auxiliary bit.  The input and
output constants are arbitrary and need not agree, so the obstruction also applies to the paper's
more permissive restriction-and-deletion semantics. -/
theorem oneAux_not_faceRealizes_twoBitDoubleNot
    (ambient : BoolPerm (Fin 2 ⊕ Fin 1)) (hgenerated : ThreeBitGenerated (Fin 2 ⊕ Fin 1) ambient)
    (input output : BoolWord (Fin 1)) :
    ¬FaceRealizes ambient input output twoBitDoubleNot := by
  intro hrealizes
  have hsource := zeroDataWithOneAux_atMostOneTrue input
  have hafter := hgenerated.preservesAtMostOneTrue hsource
  rw [hrealizes (fun _ : Fin 2 ↦ false)] at hafter
  exact twoBitDoubleNot_zero_not_atMostOneTrue output hafter

end Synthesis

end Toffoli
